- filename: DBLP.bib
  search_type: FEED
  source_name: Information & Management
  source_url: ''
  search_parameters:
  - endpoint: dblp
    params: SCOPE venue_key='journals/iam' AND journal_abbreviated='Inf. Manag.'
  last_sync: null
  comment: ''
  outlet: null
  sub_dir_pattern: null
- filename: CROSSREF.bib
  search_type: FEED
  source_name: CROSSREF
  source_url: CROSSREF.bib
  search_parameters:
    - endpoint: crossref
      params: SCOPE journal_issn='0378-7206'
  last_sync: null
  comment: ''
  outlet: null
  sub_dir_pattern: null
- filename: pdfs.bib
  search_type: FEED
  source_name: IM
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH journal='Information & Management' AND sub_dir_pattern='volume_number'
  comment: NA
